services:
  accounts:
    image: radomkhoem/accounts:jdk21
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - rdm-bank
  cards:
    image: radomkhoem/cards:jdk21
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - rdm-bank
  loans:
    image: radomkhoem/loans:jdk21
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - rdm-bank

networks:
  rdm-bank:
    driver: bridge